version: '3.3'
services:
  redis-master:
    build: .
  redis-slave:
    build: .
    depends_on:
      - redis-master
    environment:
      SLAVEOF: "redis-master 6379"
  redis-sentinel-1:
    build: .
    command: ["sentinel"]
    environment:
      SENTINEL_PORT: 5001
      MASTER_IP: redis-master
      MASTER_PORT: 6379
      QUORUM_NO: 2
      DOWN_AFTER: 5000
      FAILOWER_TIMEOUT: 60000
      PARALLEL_SYNC: 1
    depends_on:
      - redis-master
  redis-sentinel-2:
    build: .
    command: ["sentinel"]
    environment:
      SENTINEL_PORT: 5002
      MASTER_IP: redis-master
      MASTER_PORT: 6379
      QUORUM_NO: 2
      DOWN_AFTER: 5000
      FAILOWER_TIMEOUT: 60000
      PARALLEL_SYNC: 1
    depends_on:
      - redis-master
  redis-sentinel-3:
    build: .
    command: ["sentinel"]
    environment:
      SENTINEL_PORT: 5003
      MASTER_IP: redis-master
      MASTER_PORT: 6379
      QUORUM_NO: 2
      DOWN_AFTER: 5000
      FAILOWER_TIMEOUT: 60000
      PARALLEL_SYNC: 1
    depends_on:
      - redis-master
